server {
  listen 80;

  # Use AWS VPC DNS resolver
  # 169.254.169.253 = AWS DNS in VPC
  # valid=10s = re-resolve every 10 seconds
  #resolver 169.254.169.253 valid=10s;
  resolver 127.0.0.11 valid=10s;

  location / {
    root /usr/share/nginx/html;
    index index.html;
  }

  location /api/ {
    # Use variable so nginx doesn't resolve at startup!
    # With variable = lazy resolution at request time!
    #set $gateway "gateway.micro-dash-dev.local";
    set $gateway "gateway";
    proxy_pass http://$gateway:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
