FROM nginx:1.27-alpine3.21
# In frontend/Dockerfile, add this after your FROM line
RUN apk update && apk upgrade --no-cache
COPY index.html /usr/share/nginx/html/index.html
COPY default.conf /etc/nginx/conf.d/default.conf
