# FROM node:18-alpine as builder
# WORKDIR /app
# COPY package.json .
# RUN npm install
# COPY . .
# CMD ["node","app.js"]
# single build 139 mb 
#gateway
from node:18-alpine as builder
workdir /app
copy package*.json ./
run npm ci --omit=dev
copy . . 
from gcr.io/distroless/nodejs22-debian12
workdir /app
copy --from=builder /app /app
user nonroot
cmd ["server.js"]
