#single build -> 134mb
# FROM node:18-alpine
# WORKDIR /app
# COPY package.json .
# RUN npm install
# COPY . .
# CMD ["node","app.js"]

#order-service
#multi build -> 149 mb
# FROM node:18-alpine AS build
FROM node:22-slim as build
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
FROM gcr.io/distroless/nodejs22-debian13
COPY --from=build /app /app
WORKDIR /app
USER 65532
CMD ["server.js"]
