#single build -> 134mb
# FROM node:18-alpine
# WORKDIR /app
# COPY package.json .
# RUN npm install
# COPY . .
# CMD ["node","app.js"]


#multi build -> 149 mb
FROM node:22-alpine AS build
WORKDIR /app
COPY package.json  package-lock.json .
RUN npm ci
COPY . .
FROM gcr.io/distroless/nodejs22-debian12
WORKDIR /app
COPY --from=build /app .
USER 65532
CMD ["server.js"]